import React, { useState, useEffect } from 'react';
import { Radio, AlertTriangle, Shield, Clock } from 'lucide-react';

export default function LiveAlertFeed() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchAlerts = async () => {
    try {
      const res = await fetch('/api/dashboard/alerts');
      if (res.ok) {
        const data = await res.json();
        setAlerts(data);
      }
    } catch (err) {
      console.error("Failed to load alerts", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
    const interval = setInterval(fetchAlerts, 5000);
    return () => clearInterval(interval);
  }, []);

  if (loading && alerts.length === 0) {
    return <div className="p-8 text-center text-slate-400">Loading live telemetry...</div>;
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="glass-panel p-6 rounded-xl border border-border flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Radio className="w-5 h-5 text-primary animate-pulse" />
            Live SOC Telemetry Feed
          </h2>
          <p className="text-sm text-slate-400 mt-1">Real-time alerts generated by the ORION Risk Engine</p>
        </div>
        <div className="flex items-center gap-2 text-xs font-mono px-3 py-1 bg-card rounded border border-border">
          <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
          LISTENING
        </div>
      </div>

      <div className="space-y-3">
        {alerts.length === 0 ? (
          <div className="glass-panel p-8 rounded-xl border border-border text-center text-slate-400">
            No alerts generated yet. Ingest events to see live telemetry.
          </div>
        ) : (
          alerts.map((alert) => (
            <div key={alert.alert_id} className="glass-panel p-4 rounded-xl border border-border flex items-start gap-4 glass-panel-hover">
              <div className={`p-2 rounded-lg ${alert.severity === 'CRITICAL' ? 'bg-severity-critical/20 text-severity-critical' : alert.severity === 'HIGH' ? 'bg-severity-high/20 text-severity-high' : 'bg-severity-medium/20 text-severity-medium'}`}>
                <AlertTriangle className="w-5 h-5" />
              </div>
              <div className="flex-1">
                <div className="flex items-start justify-between">
                  <h4 className="text-sm font-bold text-white">{alert.message}</h4>
                  <span className="text-[10px] text-slate-400 font-mono flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {new Date(alert.created_at).toLocaleTimeString()}
                  </span>
                </div>
                <div className="flex items-center gap-3 mt-2 text-xs">
                  <span className="text-slate-400 font-mono px-2 py-0.5 rounded bg-surface border border-border">
                    {alert.alert_id}
                  </span>
                  <span className="text-slate-400 font-mono px-2 py-0.5 rounded bg-surface border border-border">
                    INC: {alert.incident_id}
                  </span>
                  <span className={`font-mono px-2 py-0.5 rounded border ${alert.acknowledged ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30' : 'bg-amber-500/10 text-amber-400 border-amber-500/30'}`}>
                    {alert.acknowledged ? 'ACKNOWLEDGED' : 'NEW'}
                  </span>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
